interface Dictionary<T> {
    [Key: string]: T;
}
declare var DbNetSuiteCore: any;
declare var controlArray: Dictionary<ComponentControl>;
declare class ComponentControl {
    controlId: string;
    form: HTMLFormElement;
    parentControl: ComponentControl;
    childControls: Dictionary<ComponentControl>;
    controlContainer: HTMLElement;
    eventHandlers: {};
    searchDialog: SearchDialog;
    formBody: HTMLElement;
    formMessage: HTMLDivElement;
    currentValidationRow: HTMLTableRowElement;
    constructor(controlId: any);
    setCaption(text: any): void;
    protected isControlEvent(evt: any): any;
    protected invokeEventHandler(eventName: any, args?: {}): boolean;
    protected eventHandlerAttached(eventName: any, args?: {}): boolean;
    protected toast(text: any, style?: string, delay?: number): void;
    protected formSelector(): string;
    protected controlElements(selector: any): NodeListOf<any>;
    controlElement(selector: any): any;
    protected triggerName(evt: any): any;
    protected triggerElement(evt: any): HTMLElement;
    protected updateLinkedControls(linkedIds: string, primaryKey: string, url?: string): void;
    notifyParent(records: boolean): void;
    childLoaded(records: boolean): void;
    dataSourceIsFileSystem(): boolean;
    protected loadFromParent(primaryKey: string): void;
    protected toolbarExists(): any;
    protected isElementLoaded: (selector: any) => Promise<any>;
    protected removeClass(selector: string, className: string): void;
    protected addClass(selector: string, className: string): void;
    getButton(name: any): HTMLButtonElement;
    buttonSelector(buttonType: any): string;
    protected setPageNumber(pageNumber: number, totalPages: number, name: string): void;
    protected assignSearchDialog(): void;
    protected validateSearchDialog(evt: any): boolean;
    protected formMode(): string;
    protected formModified(): boolean;
    protected elementModified(el: HTMLFormElement, unappliedCheck?: boolean): boolean;
    protected errorHighlighted(container: HTMLElement): boolean;
    protected triggerCommit(): void;
    formControlValue(columnName: string, row?: HTMLTableRowElement): any;
    formControlDbValue(columnName: string, row?: HTMLTableRowElement): any;
    private elementValue;
    formControl(columnName: string, row?: HTMLTableRowElement): HTMLFormElement;
    protected getElementName(el: HTMLFormElement): string;
    protected cleanString(value: any): any;
    protected wasChecked(value: string): boolean;
    protected setMessage(message: string, type?: string): void;
    protected clearErrorMessage(): void;
    protected reassignFormCheckboxValue(): void;
    private nextInputElement;
    protected getFormModification(container: HTMLElement): RowModification;
}
