interface RowModification {
    modified: boolean;
    columns: Array<string>;
}
declare class GridControl extends ComponentControl {
    private bgColourClass;
    private textColourClass;
    viewDialog: ViewDialog;
    selectedRow: HTMLTableRowElement;
    jsonData: [any];
    deferredLoad: boolean;
    constructor(gridId: string, deferredLoad: boolean);
    afterRequest(evt: any): void;
    private setTableWidth;
    private showTextTooltip;
    private hideTextTooltip;
    private initialise;
    checkForVisibility(): void;
    configRequest(evt: any): void;
    afterSettle(evt: any): void;
    private validateUpdate;
    beforeRequest(evt: any): void;
    private getModifiedRows;
    columnSeriesData(columnName: string): any[];
    private getPropertyName;
    rowSeriesData(columnSeriesName: string, columnSeriesValue: string, columnNames: string[]): any[];
    refreshPage(): void;
    private invokeCellTransform;
    private configureNavigation;
    private rowSelection;
    private configureSortIcon;
    private showHideNestedGrid;
    private refresh;
    private updateMultiRowSelect;
    private selectRow;
    private selectedValuesChanged;
    private updateLinkedGrids;
    private clearHighlighting;
    private clearRowHighlight;
    private copyTableToClipboard;
    private copyElementToClipboard;
    previousRow(): void;
    nextRow(): void;
    private download;
    private openWindow;
    private downloadFile;
    private showIndicator;
    private hideIndicator;
    private indicator;
    private rowSelector;
    private multiRowSelectAllSelector;
    private multiRowSelectSelector;
    gridControlElement(selector: any): HTMLElement;
    private selectedValues;
    columnCells(columnName: any): NodeListOf<HTMLTableCellElement>;
    heading(columnName: any): HTMLTableCellElement;
    columnCell(columnName: string, row: HTMLTableRowElement): HTMLTableCellElement;
    columnValue(columnName: string, row?: HTMLTableRowElement): any;
    private hasFormControl;
    highlightError(columnName: string, row?: HTMLTableRowElement): void;
    private configureFormControls;
    private getTextWidth;
}
